# List of topics to be recored along with the type

save_folder: /opt/ros_ws/src/data_collection/

topics:
  # - /oculus/my_right_controller_1_Pose : Pose
  # - /oculus/my_right_controller_1/joy: Joy
  - /franka_state_controller/franka_states: obs
  - /cartesian_impedance_controller/desired_pose: obs
  - /cartesian_impedance_controller/desired_gripper_state: obs
  - /franka_gripper/joint_states: obs
  - /franka_state_controller/joint_states_desired: obs
  - /franka_state_controller/O_T_EE: obs
  - /franka_state_controller/ee_pose: obs
  - /franka_state_controller/joint_states: obs

save_action: true

video_topics:
  - /zedA/zed_node_A/left/image_rect_color : obs
  - /zedB/zed_node_B/left/image_rect_color : obs




