# List of topics to be recored along with the type

save_folder: /opt/ros_ws/src/data_collection/robot-policy-eval/

topics:
  - /franka_state_controller/franka_states: FrankaState
  - /cartesian_impedance_controller/desired_pose: PoseStamped
  - /cartesian_impedance_controller/desired_gripper_state: PointStamped

video_topics:
  - /zedA/zed_node_A/left/image_rect_color : video
  - /zedB/zed_node_B/left/image_rect_color : video
